# Generated by Django 5.2.6 on 2025-09-07 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg., Room 101, Lab A', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg., Section A, Section B', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_theory_hours', models.PositiveIntegerField(default=3)),
                ('required_tutorial_hours', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.subject')),
            ],
            options={
                'unique_together': {('subject', 'section')},
            },
        ),
        migrations.CreateModel(
            name='FacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.CharField(choices=[('ALL', 'All Classes (Theory and Tutorial)'), ('THEORY', 'Theory Only'), ('TUTORIAL', 'Tutorial Only')], default='ALL', help_text='Defines which part of the course this faculty member teaches.', max_length=20)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='scheduler_app.courseoffering')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='scheduler_app.faculty')),
            ],
            options={
                'unique_together': {('course_offering', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3'), (4, 'Day 4'), (5, 'Day 5'), (6, 'Day 6')])),
                ('period', models.PositiveIntegerField()),
                ('class_type', models.CharField(choices=[('THEORY', 'Theory'), ('TUTORIAL', 'Tutorial')], max_length=10)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_classes', to='scheduler_app.classroom')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_classes', to='scheduler_app.faculty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_classes', to='scheduler_app.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_classes', to='scheduler_app.subject')),
            ],
            options={
                'ordering': ['day', 'period', 'section'],
                'unique_together': {('day', 'period', 'classroom'), ('day', 'period', 'faculty'), ('day', 'period', 'section')},
            },
        ),
    ]
